name: 'testing new stuff'
description: 'Get dependency and cache them'
runs: 
  using: 'composite'
  steps:
    - name: Print workspace name
      run: |
        echo "workspace name github.workspace"
        echo "nodeversion is matrix.nodeversion"
      shell: bash