name: testing check input
description: Pradeep testing some data
runs:
  using: 'composite'
  steps:
    - name: First Step
      id: ststep
      run: |
       echo 'some testing in 1st step'
      shell: bash
    - name: Second step
      id: ndstep
      run: |
        echo 'I am in second step'
      shell: bash