name: Pradeep Checks something
run-name: Something new ${{ github.actor }}
on: 
    workflow_dispatch: 
        inputs:
            username:
                default: pradeep
                description: Enter user name
                required: true
                type: string
            password:
                default: password
                description: Enter password
                options:
                    - password1
                    - password2
                    - password
                type: choice
    pull_request: 
        types: opened
jobs:
    firstjob:
        strategy:
            matrix:
                nodeversion: [1,2,3]
                osversion: [2,6]
                exclude:
                    - nodeversion: 3
                      osversion: 6
                include: 
                    - nodeversion: 10
                      osversion: 16
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v3
            - name: Print workspace name
              run: |
                echo "workspace name ${{ github.workspace }}"
                echo "nodeversion is ${{ matrix.nodeversion }}"
    secondjob:
        name: callable workflow from other workflow
        uses: ./.github/workflows/workflowcallable.yml
        with:
            username: ${{ inputs.username }}
            password: ${{ inputs.password }}
        secrets: 
            somekaka: ${{ secrets.REPO_XYZ }}
    thirdjob:
        name: third job
        needs: secondjob
        runs-on: ubuntu-latest
        steps:
            - name: some data
              env:
                data1: ${{ github.event.pull_request.title }} 
              run: |
                echo "${{ needs.secondjob.outputs.somedata  }}"
                echo "$data1  token is --->"



