name: if condition example
on:
    workflow_dispatch:        
        inputs:
            browsername:
                type: string
                default: chrome
                required: true
                description: enter browser name
            gender:
                type: choice
                required: true
                default: male
                description: enter your gender
                options:
                    - male
                    - female
                    - na
                    
run-name: java jmal e
jobs:
    firstjob:
        name: My first job
        runs-on: ubuntu-latest
        steps:
            - name: first step
              id: fstid
              run: |
                echo "Browser name ${{ inputs.browsername }} ----> ${{ inputs.gender }}"
    secondjob:
        name: workflowjob
        uses: ./.github/workflows/worflowcall.yml
        with: 
            browsername: ${{ inputs.browsername }}
            gender: ${{ inputs.gender }}
        secrets: 
            hello: ${{ secrets.REPO_XYZ }}
    thirdjob:
        name: thirdjob
        needs: secondjob
        runs-on: ubuntu-latest
        steps:
            - name: hello jamal
              run: |
                echo "hello how are you ${{ needs.secondjob.outputs.result }}"
        

