name: learning something new
run-name: running few tests
on:
    workflow_run: 
        workflows: [Strategy example]
        types: completed
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
jobs:
    log-the-inputs:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "Log level: $${{ env.ENVIRONMENT }}"
            echo "Tags: $TAGS"
            echo "Environment: $ENVIRONMENT" 
          env:
            LEVEL: ${{ inputs.logLevel }}
            TAGS: ${{ inputs.tags }}
            ENVIRONMENT: ${{ inputs.environment }}
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
         - run: echo 'The triggering workflow passed'
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
         - run: echo 'The triggering workflow failed'

