name: Usable and Reusable Flow
run-name: Testing reusability
on:
  workflow_dispatch:
    inputs:
      branchname:
        required: true
        type: string
      urname:
        required: false
        type: string

jobs:
  firstjob:
    if: ${{ inputs.branchname != 'master' }}
    uses: ./.github/workflows/reusable.yml
    with:
     branchname: "main"
     urname: "John Doe"
        
