name: Pradeep Learning
on: workflow_dispatch
run-name: Something Data
jobs:
    first-job: 
        name: Testing my first job
        runs-on: ubuntu-latest
        steps:
            - name: first step
              id: run-tests
              run: |
                echo 'Hello how are you'
                exit 1
            - name: second step
              if: failure() && steps.run-tests.outcome == 'failure'
              run: |
                echo 'keka taka ${{ github.ref }}'                           

              

        




  
  
