name: Usable and Reusable Flow
run-name: Testing reusability
on:
  workflow_dispatch:
    inputs:
      branchname:
        required: true
        type: string
      urname:
        required: false
        type: string

jobs:
  firstjob:
    if: ${{ inputs.branchname != 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: My First Step
        run: |
          echo "Hello world ${{ inputs.branchname }} ----- ${{ inputs.urname }} ${{ github.workspace }}"
