name: Pradeep Learning
on: workflow_dispatch
run-name: Something Data
jobs:
    first-job: 
        name: Testing my first job
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: |
                echo 'Hello how are you'
                echo 10/0
            - name: second step
              run: |
                echo 'keka taka ${{ github.ref }}'                           

              

        




  
  
