name: Usable and Reusable Flow
run-name: Testing reusability
on:
    workflow_dispatch: 
        inputs:
            branchname:
                default: master
                description: Enter branch name
                required: true
                type: string
            urname:
                default: pradeep
                description: enter your name
                required: true
                type:  string
jobs:
  firstjob:
    if: ${{ inputs.branchname != 'master'  }}
    runs-on: ubuntu-latest
    steps:
        - name: checkout the code
          uses: actions/checkout@v3
        - name: calling reusable flow
          uses: ./.github/workflows/reusable.yml
          with:
              bname: mama majare
          
        - name: my first step
          run: |
            echo "Hello world ${{ inputs.branchname }} ----- ${{ inputs.urname }}"
