name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      branchname:
        required: true
        type: string
      urname:
        required: false
        type: string
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Branch: ${{ inputs.branchname }}"
          echo "User Name: ${{ inputs.urname }}"
