
name: Wflow call flow
on: 
    workflow_call: 
        inputs:
            bname:
                default: matres
                description: Enter branch name
                required: false
                type: string
run-name: Testing few  things
jobs:
    hellofelow:
        runs-on: ubuntu-latest
        steps:
            - name: Enter something
              run: |
                echo "Hello world ${{ inputs.bname }}"

