name: second flow
on: [workflow_dispatch]
run-name: Testing my knowledge
jobs:
  First-job: 
    name: My Job to Test
    runs-on: ubuntu-latest
    outputs:
      handle: ${{ steps.step1.outputs.handle }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: some code
        id: step1
        run: |
          ls ${{ github.workspace }}
          files="${{ github.workspace }}"
          echo "handle=$files" >> "$GITHUB_OUTPUT"
          echo "runner name ${{runner.name}}"
  Second-job:
    name: hello how
    needs: First-job
    runs-on: ubuntu-latest
    steps: 
      - name: sample code
        run: |
          echo "The value is ${{needs.First-job.outputs.handle}}"
          echo "runner name ${{runner.name}}"
        
    
