name: Strategy example
run-name: testing example
on: workflow_dispatch
jobs: 
    firstjob:
        name: first job
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodeversion: [1,3,5,7]
                subversion: [2,4,6]
        steps:
            - name: hello steps
              run: |
                echo "Node version ${{ matrix.nodeversion }} ---> ${{ matrix.subversion }}"

        