name: workflow call example
run-name: example code
env:
  ghubEx: pradeep
  USERNAME: PSPS
  PASSWORD:  password
on:
    workflow_call: 
        inputs:
          user: 
            required: true
            type: string
          pwd:
            required: true
            type: string
jobs:
  job1:
     name: Sample Example workflow
     runs-on: ubuntu-latest
     steps:
        - name: inputs values
          run: |
            echo "The values are ${{ inputs.pwd }} -----> ${{ inputs.user }}"
